name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Copy files via rsync
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD_QB }}
      run: |
        sshpass -p "$SSH_PASSWORD" rsync -az --delete -e "ssh -p 3591 -o StrictHostKeyChecking=no" . admissions@103.10.27.59:/var/www/html/

    - name: Execute remote commands using SSH
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD_QB }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p 3591 admissions@103.10.27.59 <<EOF
        # Commands to execute after deployment
        cd /var/www/html/
        echo "Deployment complete!"
        EOF
