name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH client and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client sshpass

    - name: Copy files via rsync
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        rsync -az -e "sshpass -p $SSH_PASSWORD ssh -p 3591 -o StrictHostKeyChecking=no" ./ admissions@admissions-uvm:/var/www/html/
        
    - name: Execute remote commands using SSH
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p 3591 admissions@admissions-uvm << 'EOF'
        # Add more commands as needed
        EOF
